theme: jekyll-theme-minimal
title: 跑步英雄传 | RunQuest
description: 跑步英雄传 (RunQuest) Privacy Policy, Terms & Support
url: https://runrpg.astralogy.org
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: default
